#!/bin/bash

sudo hostnamectl set-hostname “HOST NAME HERE” && exec bash

echo '192.168.5.135 kmaster' >> /etc/hosts
echo '192.168.5.136 kworker1' >> /etc/hosts
echo '192.168.5.137 kworker2' >> /etc/hosts
echo '192.168.5.138 kworker3' >> /etc/hosts


swapoff -a
sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab


setenforce 0
sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=permissive/g' /etc/sysconfig/selinux


firewall-cmd --permanent --add-port={6443,2379,2380,10250,10251,10252,10257,10259,179}/tcp
firewall-cmd --permanent --add-port=4789/udp
firewall-cmd --reload


tee /etc/modules-load.d/containerd.conf <<EOF
overlay
br_netfilter
EOF


modprobe overlay
modprobe br_netfilter


touch /etc/sysctl.d/k8s.conf
echo 'net.bridge.bridge-nf-call-iptables  = 1' >> /etc/sysctl.d/k8s.conf
echo 'net.ipv4.ip_forward = 1' >> /etc/sysctl.d/k8s.conf
echo 'net.bridge.bridge-nf-call-ip6tables = 1' >> /etc/sysctl.d/k8s.conf
sysctl --system


dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
dnf install containerd.io -y


containerd config default | sudo tee /etc/containerd/config.toml >/dev/null 2>&1


sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml


systemctl restart containerd
systemctl enable --now containerd


cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://pkgs.k8s.io/core:/stable:/v1.28/rpm/
enabled=1
gpgcheck=1
gpgkey=https://pkgs.k8s.io/core:/stable:/v1.28/rpm/repodata/repomd.xml.key
exclude=kubelet kubeadm kubectl cri-tools kubernetes-cni
EOF


yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
systemctl enable --now kubelet


kubeadm init
